title: Сильный край - общественная организация в Белгороде
logo: /assets/img/logo.png
description: Наша цель объединить усилия неравнодушных людей, привлечь дополнительные ресурсы и эффективно помочь пострадавшим жителям Грайворона, Шебекина и Белгородской области.
google_analytics:
theme: jekyll-theme-minimal
